
# host配置文件地址
host_remote_address: http://host-server.com

# 临时文件
temp_file_path: hosts

# 重启进程路径
restart_exe_path: C:\Program Files\Internet Explorer\iexplore.exe

# 重启进程名称
restart_process_name: iexplore.exe

# 更新周期 秒
refresh_second: 10

# 运行日志
log_file: c:/xtt.log